name: Deploy OpenMeteo Docs

on:
  push:
    branches:
      - main
    paths:
      - 'e2e_openmeteo/docs/**'
      - 'e2e_openmeteo/mkdocs.yml'
      - '.github/workflows/deploy-openmeteo-docs.yml'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          key: ${{ github.ref }}
          path: .cache
      
      - name: Install MkDocs Material
        run: |
          pip install mkdocs-material
          pip install pymdown-extensions
      
      - name: Deploy MkDocs
        working-directory: e2e_openmeteo
        run: |
          mkdocs gh-deploy --force --clean --verbose

